import 'package:netflix_clone/models/movies_model/movies_model.dart';

Map<String, List<MoviesModel>> movies = {
  'Home': [],
  'Malayalam': [
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/thudarum.jpg',
      titl: 'Thudarum',
      description:
          "Thudarum is an upcoming crime drama directed by Tharun Moorthy that delves into mystery and moral conflict in a small Kerala town.",
      istop10: true,
      releaseYear: '2025',
      video: 'assets/video/movies_video/malayalam/thudarum.mp4',
      newreleased: true,
      agerating: 'U/A 13+',
      duration: '2h 30m',
      cast: ['Mohanlal', 'Shobhana', 'Bharathiraja', 'Thomas Mathew'],
      director: 'Tharun Moorthy',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/varathan.jpg',
      titl: 'Varathan',
      description:
          "After losing his job abroad, Aby returns to Kerala with his wife and faces unexpected events that test their courage.",
      istop10: false,
      releaseYear: '2018',
      video: 'assets/video/movies_video/malayalam/varathan.mp4',
      newreleased: false,
      agerating: 'U/A 18+',
      duration: '2h 10m',
      cast: [
        'Fahadh Faasil',
        'Aishwarya Lekshmi',
        'Sharafudheen',
        'Dileesh Pothan',
      ],
      director: 'Amal Neerad',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/virus.jpg',
      titl: 'Virus',
      description:
          "Based on the true events of the 2018 Nipah virus outbreak in Kerala, showcasing bravery and teamwork of healthcare workers.",
      istop10: true,
      releaseYear: '2019',
      video: 'assets/video/movies_video/malayalam/virus.mp4',
      newreleased: false,
      agerating: 'U/A 13+',
      duration: '2h 32m',
      cast: [
        'Kunchacko Boban',
        'Revathi',
        'Parvathy Thiruvothu',
        'Sreenath Bhasi',
      ],
      director: 'Aashiq Abu',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/sitaramam.jpg',
      titl: 'Sita Ramam',
      description:
          "An epic love story between a soldier and a woman who writes him letters, set across decades and borders.",
      istop10: false,
      releaseYear: '2022',
      video: 'assets/video/movies_video/malayalam/sitaramam.mp4',
      newreleased: false,
      agerating: 'U/A 13+',
      duration: '2h 43m',
      cast: [
        'Dulquer Salmaan',
        'Mrunal Thakur',
        'Rashmika Mandanna',
        'Sumanth',
      ],
      director: 'Hanu Raghavapudi',
    ),

    MoviesModel(
      true,
      thumbail: 'assets/images/movies/malayalam/Romancham.jpg',
      titl: 'Romancham',
      description:
          "A group of friends experiment with a Ouija board, leading to hilarious and spooky consequences.",
      istop10: true,
      releaseYear: '2023',
      video: 'assets/video/movies_video/malayalam/Romancham.mp4',
      newreleased: true,
      agerating: 'U/A 13+',
      duration: '2h 10m',
      cast: ['Soubin Shahir', 'Arjun Ashokan', 'Sajin Gopu', 'Abin Bino'],
      director: 'Jithu Madhavan',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/premam.jpg',
      titl: 'Premam',
      description:
          "A coming-of-age romantic story that follows George’s love journey through three stages of his life.",
      istop10: false,
      releaseYear: '2015',
      video: 'assets/video/movies_video/malayalam/premam.mp4',
      newreleased: false,
      agerating: 'U',
      duration: '2h 37m',
      cast: [
        'Nivin Pauly',
        'Sai Pallavi',
        'Madonna Sebastian',
        'Anupama Parameswaran',
      ],
      director: 'Alphonse Puthren',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/Premalu.jpg',
      titl: 'Premalu',
      description:
          "A fun-filled romantic comedy set in Hyderabad, following Sachin’s misadventures in love and friendship.",
      istop10: true,
      releaseYear: '2024',
      video: 'assets/video/movies_video/malayalam/premalu.mp4',
      newreleased: true,
      agerating: 'U/A 13+',
      duration: '2h 26m',
      cast: ['Naslen', 'Mamitha Baiju', 'Shyam Mohan', 'Akhila Bhargavan'],
      director: 'Girish A D',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/officer.jpg',
      titl: 'Officer on Duty',
      description:
          "A fast-paced action thriller following a determined police officer’s fight against corruption.",
      istop10: true,
      releaseYear: '2025',
      video: 'assets/video/movies_video/malayalam/virus.mp4',
      newreleased: true,
      agerating: 'U/A 16+',
      duration: '2h 18m',
      cast: ['Asif Ali', 'Aparna Balamurali', 'Lal', 'Vineeth Sreenivasan'],
      director: 'Joshiy',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/mayanadi.jpg',
      titl: 'Mayaanadhi',
      description:
          "A beautiful yet tragic love story between an aspiring actress and a fugitive lover.",
      istop10: false,
      releaseYear: '2017',
      video: 'assets/video/movies_video/malayalam/sitaramam.mp4',
      newreleased: false,
      agerating: 'U/A 13+',
      duration: '2h 16m',
      cast: [
        'Tovino Thomas',
        'Aishwarya Lekshmi',
        'Harish Uthaman',
        'Leona Lishoy',
      ],
      director: 'Aashiq Abu',
    ),

    MoviesModel(
      true,
      thumbail: 'assets/images/movies/malayalam/luckybaskhar.jpg',
      titl: 'Lucky Baskhar',
      description:
          "A middle-class man discovers a mysterious opportunity that changes his financial destiny.",
      istop10: true,
      releaseYear: '2024',
      video: 'assets/video/movies_video/malayalam/lucifer.mp4',
      newreleased: true,
      agerating: 'U/A 13+',
      duration: '2h 30m',
      cast: [
        'Dulquer Salmaan',
        'Meenakshi Chaudhary',
        'R. Sarathkumar',
        'Prasanna',
      ],
      director: 'Venky Atluri',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/lucifer.jpg',
      titl: 'Lucifer',
      description:
          "After a political leader’s death, power struggles erupt as hidden truths unfold in his family and party.",
      istop10: false,
      releaseYear: '2019',
      video: 'assets/video/movies_video/malayalam/lucifer.mp4',
      newreleased: false,
      agerating: 'U/A 16+',
      duration: '2h 55m',
      cast: ['Mohanlal', 'Vivek Oberoi', 'Manju Warrier', 'Tovino Thomas'],
      director: 'Prithviraj Sukumaran',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/lokah.jpg',
      titl: 'Lokah: Chapter 1 – Chandra',
      description:
          "A Malayalam superhero film that follows Chandra, a young woman who discovers extraordinary powers and must embrace her destiny to protect humanity from an ancient threat.",
      istop10: true,
      releaseYear: '2025',
      video: 'assets/video/movies_video/malayalam/lokaj.mp4',
      newreleased: true,
      agerating: 'U/A 13+',
      duration: '2h 35m',
      cast: [
        'Kalyani Priyadarshan',
        'Raj B. Shetty',
        'Suraj Venjaramoodu',
        'Sanal Aman',
      ],
      director: 'Dominic Arun',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/koode.jpg',
      titl: 'Koode',
      description:
          "A heartfelt drama about a man reconnecting with his family and past after returning home.",
      istop10: false,
      releaseYear: '2018',
      video: 'assets/video/movies_video/malayalam/koode.mp4',
      newreleased: false,
      agerating: 'U',
      duration: '2h 35m',
      cast: [
        'Prithviraj Sukumaran',
        'Nazriya Nazim',
        'Parvathy Thiruvothu',
        'Roshan Mathew',
      ],
      director: 'Anjali Menon',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/kannur.jpg',
      titl: 'Kannur Squad',
      description:
          "A gripping action thriller following a special police team tracking a criminal gang across India.",
      istop10: true,
      releaseYear: '2023',
      video: 'assets/video/movies_video/malayalam/varathan.mp4',
      newreleased: false,
      agerating: 'U/A 16+',
      duration: '2h 41m',
      cast: ['Mammootty', 'Rony David', 'Azees Nedumangad', 'Shabareesh Varma'],
      director: 'Roby Varghese Raj',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/joji.jpg',
      titl: 'Joji',
      description:
          "A modern-day adaptation of Shakespeare’s Macbeth set in a Kerala Christian family.",
      istop10: true,
      releaseYear: '2021',
      video: 'assets/video/movies_video/malayalam/joji.mp4',
      newreleased: false,
      agerating: 'U/A 16+',
      duration: '1h 53m',
      cast: ['Fahadh Faasil', 'Basil Joseph', 'Unnimaya Prasad', 'Sunny PN'],
      director: 'Dileesh Pothan',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/Ishq.jpg',
      titl: 'Ishq',
      description:
          "A romantic thriller exploring the dark side of moral policing and relationships.",
      istop10: false,
      releaseYear: '2019',
      video: 'assets/video/movies_video/malayalam/premalu.mp4',
      newreleased: false,
      agerating: 'U/A 18+',
      duration: '2h 14m',
      cast: ['Shane Nigam', 'Ann Sheetal', 'Leona Lishoy', 'Shine Tom Chacko'],
      director: 'Anuraj Manohar',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/goatlife.jpg',
      titl: 'Goat Life',
      description:
          "Based on a true story of an Indian migrant worker’s struggle and survival in the Middle East.",
      istop10: true,
      releaseYear: '2024',
      video: 'assets/video/movies_video/malayalam/Romancham.mp4',
      newreleased: false,
      agerating: 'U/A 16+',
      duration: '2h 51m',
      cast: [
        'Prithviraj Sukumaran',
        'Jimmy Jean-Louis',
        'Amala Paul',
        'KR Gokul',
      ],
      director: 'Blessy',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/arm.jpg',
      titl: 'Aavesham',
      description:
          "Three students befriend a quirky gangster in Bangalore, leading to chaos and comedy.",
      istop10: true,
      releaseYear: '2024',
      video: 'assets/video/movies_video/malayalam/thudarum.mp4',
      newreleased: true,
      agerating: 'U/A 13+',
      duration: '2h 35m',
      cast: ['Fahadh Faasil', 'Hipzster', 'Mithun Jai Shankar', 'Sajin Gopu'],
      director: 'Jithu Madhavan',
    ),

    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/ambili.jpg',
      titl: 'Ambili',
      description:
          "A simple-minded man with a pure heart brings warmth and kindness to everyone he meets.",
      istop10: true,
      releaseYear: '2019',
      video: 'assets/video/movies_video/malayalam/ambili.mp4',
      newreleased: false,
      agerating: 'U',
      duration: '2h 20m',
      cast: ['Soubin Shahir', 'Naveen Nazim', 'Tanvi Ram', 'Jaffer Idukki'],
      director: 'Johnpaul George',
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/malayalam/2018.jpg',
      titl: '2018',
      description:
          "Based on the real-life 2018 Kerala floods, the film tells inspiring stories of human courage and unity.",
      istop10: true,
      releaseYear: '2023',
      video: 'assets/video/movies_video/malayalam/joji.mp4',
      newreleased: false,
      agerating: 'U/A 13+',
      duration: '2h 38m',
      cast: [
        'Tovino Thomas',
        'Kunchacko Boban',
        'Aparna Balamurali',
        'Asif Ali',
      ],
      director: 'Jude Anthany Joseph',
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/malayalam/Padakkalam.jpeg',
      titl: 'Padakkalam',
      description:
          "Four students face a supernatural adventure when their new professor turns their world upside down.",
      istop10: false,
      releaseYear: '2025',
      video: 'assets/video/movies_video/malayalam/premalu.mp4',
      newreleased: true,
      agerating: 'U',
      duration: '123 minutes',
      cast: [
        'Suraj Venjaramoodu as Professor Shaji K K',
        'Sharaf U Dheen as Professor Renjith',
        'Sandeep Pradeep as Jithin',
        'Saaf as Kannan',
      ],
      director: 'Manu Swaraj',
    ),
  ],
  'Hindi': [
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/hindi/aedilhe.jpg',
      titl: 'Ae Dil Hai Mushkil',
      description:
          'A complex love story that explores unrequited love, friendship, and heartbreak.',
      istop10: true,
      releaseYear: '2016',
      video: 'assets/video/movies_video/hindi/aedilhai.mp4',
      newreleased: false,
      agerating: 'U/A 13+',
      duration: '2h 38m',
      cast: ['Ranbir Kapoor', 'Anushka Sharma', 'Aishwarya Rai Bachchan'],
      director: 'Karan Johar',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/dilwale.jpg',
      titl: 'Dilwale',
      description:
          'A mix of romance, action, and comedy as two lovers reunite after years of separation.',
      istop10: false,
      releaseYear: '2015',
      video: 'assets/video/movies_video/hindi/dilwale.mp4',
      newreleased: false,
      agerating: 'U/A',
      duration: '2h 38m',
      cast: ['Shah Rukh Khan', 'Kajol', 'Varun Dhawan', 'Kriti Sanon'],
      director: 'Rohit Shetty',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/dilbechara.jpg',
      titl: 'Dil Bechara',
      description:
          'An emotional journey of love and life between two young cancer patients.',
      istop10: true,
      releaseYear: '2020',
      video: 'assets/video/movies_video/hindi/dilbechara.mp4',
      newreleased: false,
      agerating: 'U/A',
      duration: '1h 41m',
      cast: ['Sushant Singh Rajput', 'Sanjana Sanghi'],
      director: 'Mukesh Chhabra',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/12th.jpg',
      titl: '12th Fail',
      description:
          'Based on a true story, it follows a man who rises from poverty to become an IPS officer.',
      istop10: true,
      releaseYear: '2023',
      video: 'assets/video/movies_video/hindi/12thfail.mp4',
      newreleased: true,
      agerating: 'U/A',
      duration: '2h 27m',
      cast: ['Vikrant Massey', 'Medha Shankar'],
      director: 'Vidhu Vinod Chopra',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/hamari.jpg',
      titl: 'Hamari Adhuri Kahani',
      description: 'A story of unfulfilled love and emotional sacrifices.',
      istop10: false,
      releaseYear: '2015',
      video: 'assets/video/movies_video/hindi/hamari.mp4',
      newreleased: false,
      agerating: 'U/A',
      duration: '2h 9m',
      cast: ['Emraan Hashmi', 'Vidya Balan', 'Rajkummar Rao'],
      director: 'Mohit Suri',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/gangubhai.jpg',
      titl: 'Gangubai Kathiawadi',
      description:
          'A powerful biopic of a woman who became a force in Mumbai’s underworld.',
      istop10: false,
      releaseYear: '2022',
      video: 'assets/video/movies_video/hindi/gangubhai.mp4',
      newreleased: false,
      agerating: 'A',
      duration: '2h 36m',
      cast: ['Alia Bhatt', 'Ajay Devgn', 'Seema Pahwa'],
      director: 'Sanjay Leela Bhansali',
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/hindi/crew.jpg',
      titl: 'Crew',
      description:
          'Three air hostesses get caught in a web of deceit, money, and mayhem.',
      istop10: true,
      releaseYear: '2024',
      video: 'assets/video/movies_video/hindi/crew.mp4',
      newreleased: true,
      agerating: 'U/A',
      duration: '2h 15m',
      cast: ['Tabu', 'Kareena Kapoor Khan', 'Kriti Sanon'],
      director: 'Rajesh Krishnan',
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/hindi/bhoot.jpg',
      titl: 'Bhoot – Part One: \nThe Haunted Ship',
      description:
          'A horror thriller following a shipping officer investigating a haunted ship.',
      istop10: false,
      releaseYear: '2020',
      video: 'assets/video/movies_video/hindi/msdhoni.mp4',
      newreleased: false,
      agerating: 'A',
      duration: '2h 3m',
      cast: ['Vicky Kaushal', 'Bhumi Pednekar'],
      director: 'Bhanu Pratap Singh',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/kill.jpg',
      titl: 'Kill',
      description:
          'An action-packed thriller with intense train fight sequences.',
      istop10: true,
      releaseYear: '2024',
      video: 'assets/video/movies_video/hindi/kill.mp4',
      newreleased: true,
      agerating: 'A',
      duration: '1h 55m',
      cast: ['Lakshya', 'Raghav Juyal', 'Tanya Maniktala'],
      director: 'Nikhil Nagesh Bhat',
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/hindi/laapataaladies.jpg',
      titl: 'Laapataa Ladies',
      description:
          'A witty social satire about two brides who go missing in rural India.',
      istop10: false,
      releaseYear: '2024',
      video: 'assets/video/movies_video/hindi/laapataladies.mp4',
      newreleased: true,
      agerating: 'U',
      duration: '2h 3m',
      cast: ['Nitanshi Goel', 'Pratibha Ranta', 'Ravi Kishan'],
      director: 'Kiran Rao',
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/hindi/lalsingh.jpg',
      titl: 'Laal Singh Chaddha',
      description:
          'A retelling of Forrest Gump in an Indian context, following a kind-hearted man’s journey.',
      istop10: true,
      releaseYear: '2022',
      video: 'assets/video/movies_video/hindi/laalsingh.mp4',
      newreleased: false,
      agerating: 'U/A',
      duration: '2h 39m',
      cast: ['Aamir Khan', 'Kareena Kapoor', 'Mona Singh'],
      director: 'Advait Chandan',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/likestars.jpg',
      titl: 'Taare Zameen Par',
      description:
          'A heartwarming story about a dyslexic child and his art teacher.',
      istop10: false,
      releaseYear: '2007',
      video: 'assets/video/movies_video/hindi/aedilhai.mp4',
      newreleased: false,
      agerating: 'U',
      duration: '2h 45m',
      cast: ['Aamir Khan', 'Darsheel Safary'],
      director: 'Aamir Khan',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/lost.jpg',
      titl: 'Lost',
      description:
          'An emotional thriller about a journalist’s search for a missing man.',
      istop10: false,
      releaseYear: '2023',
      video: 'assets/video/movies_video/hindi/hamari.mp4',
      newreleased: false,
      agerating: 'U/A',
      duration: '2h 6m',
      cast: ['Yami Gautam', 'Rahul Khanna'],
      director: 'Aniruddha Roy Chowdhury',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/major.jpg',
      titl: 'Major',
      description:
          'A biopic on Major Sandeep Unnikrishnan, a hero of the 26/11 attacks.',
      istop10: true,
      releaseYear: '2022',
      video: 'assets/video/movies_video/hindi/kill.mp4',
      newreleased: false,
      agerating: 'U/A',
      duration: '2h 30m',
      cast: ['Adivi Sesh', 'Sobhita Dhulipala'],
      director: 'Sashi Kiran Tikka',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/msdhoni.jpg',
      titl: 'M.S. Dhoni: The Untold Story',
      description:
          'The inspiring journey of Indian cricketer Mahendra Singh Dhoni.',
      istop10: false,
      releaseYear: '2016',
      video: 'assets/video/movies_video/hindi/msdhoni.mp4',
      newreleased: false,
      agerating: 'U',
      duration: '3h 4m',
      cast: ['Sushant Singh Rajput', 'Kiara Advani', 'Disha Patani'],
      director: 'Neeraj Pandey',
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/hindi/october.jpg',
      titl: 'October',
      description:
          'A subtle love story about care, loss, and emotional growth.',
      istop10: true,
      releaseYear: '2018',
      video: 'assets/video/movies_video/hindi/october.mp4',
      newreleased: false,
      agerating: 'U',
      duration: '1h 55m',
      cast: ['Varun Dhawan', 'Banita Sandhu'],
      director: 'Shoojit Sircar',
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/hindi/saiyyara.jpg',
      titl: 'Saiyaara',
      description: 'A romantic drama inspired by timeless love and separation.',
      istop10: true,
      releaseYear: '2024',
      video: 'assets/video/movies_video/hindi/Saiyaara.mp4',
      newreleased: true,
      agerating: 'U/A',
      duration: '2h 18m',
      cast: [],
      director: 'Unknown',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/sanam.jpg',
      titl: 'Sanam Teri Kasam',
      description:
          'An emotional love story of heartbreak, sacrifice, and destiny.',
      istop10: true,
      releaseYear: '2016',
      video: 'assets/video/movies_video/hindi/hamari.mp4',
      newreleased: false,
      agerating: 'U/A',
      duration: '2h 34m',
      cast: ['Harshvardhan Rane', 'Mawra Hocane'],
      director: 'Radhika Rao & Vinay Sapru',
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/hindi/thamasha.jpg',
      titl: 'Tamasha',
      description:
          'A man struggles to find his true self beyond societal expectations.',
      istop10: false,
      releaseYear: '2015',
      video: 'assets/video/movies_video/hindi/tamasha.mp4',
      newreleased: false,
      agerating: 'U/A',
      duration: '2h 19m',
      cast: ['Ranbir Kapoor', 'Deepika Padukone'],
      director: 'Imtiaz Ali',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/tiger.jpg',
      titl: 'Tiger Zinda Hai',
      description:
          'A spy thriller where Indian and Pakistani agents unite to rescue hostages.',
      istop10: true,
      releaseYear: '2017',
      video: 'assets/video/movies_video/hindi/TigerZindaHai.mp4',
      newreleased: false,
      agerating: 'U/A',
      duration: '2h 41m',
      cast: ['Salman Khan', 'Katrina Kaif'],
      director: 'Ali Abbas Zafar',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/Secret Superstar (2017).jpeg',
      titl: 'Secret Superstar',
      description:
          "A 14-year-old Her journey to stardom is complicated by her abusive father and her mother support.",
      istop10: false,
      releaseYear: '2017',
      video: 'assets/video/movies_video/hindi/crew.mp4',
      newreleased: true,
      agerating: 'TV-14',
      duration: '150 minutes',
      cast: [
        'Zaira Wasim as Insia Malik',
        'Aamir Khan as Shakti Kumar',
        'Meher Vij as Najma Malik',
        'Raj Arjun as Farookh Malik',
      ],
      director: 'Advait Chandan',
    ),
  ],
  'English': [
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/arrival.jpeg",
      titl: "Arrival",
      description:
          "A linguist works to communicate with aliens who have landed on Earth.",
      istop10: true,
      releaseYear: "2016",
      video: "assets/video/movies_video/malayalam/virus.mp4",
      newreleased: true,
      agerating: "PG-13",
      duration: "1h 56m",
      cast: [
        "Amy Adams",
        "Jeremy Renner",
        "Forest Whitaker",
        "Michael Stuhlbarg",
      ],
      director: "Denis Villeneuve",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/english/Avatar.jpeg",
      titl: "Avatar",
      description:
          "A paraplegic Marine is sent to Pandora and becomes part of the Na'vi tribe.",
      istop10: true,
      releaseYear: "2009",
      video: "assets/video/movies_video/malayalam/thudarum.mp4",
      newreleased: false,
      agerating: "PG-13",
      duration: "2h 42m",
      cast: [
        "Sam Worthington",
        "Zoe Saldana",
        "Sigourney Weaver",
        "Stephen Lang",
      ],
      director: "James Cameron",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/deappool.jpeg",
      titl: "Deadpool & Wolverine",
      description:
          "Deadpool and Wolverine team up for chaotic, action-packed adventures.",
      istop10: false,
      releaseYear: "2024",
      video: "assets/video/movies_video/malayalam/premam.mp4",
      newreleased: false,
      agerating: "R",
      duration: "2h 10m",
      cast: ["Ryan Reynolds", "Hugh Jackman", "Morena Baccarin", "Josh Brolin"],
      director: "David Leitch",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/dontbreath.jpeg",
      titl: "Don't Breathe 2",
      description:
          "The blind man faces new threats while trying to protect a young girl.",
      istop10: false,
      releaseYear: "2021",
      video: "assets/video/movies_video/malayalam/joji.mp4",
      newreleased: false,
      agerating: "R",
      duration: "1h 38m",
      cast: ["Stephen Lang", "Bridger Zadina", "Madelyn Grace", "Jane Levy"],
      director: "Rodo Sayagues",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/Extraction2.jpeg",
      titl: "Extraction II",
      description:
          "Tyler Rake returns for a mission that tests his limits and resolve.",
      istop10: true,
      releaseYear: "2023",
      video: "assets/video/movies_video/malayalam/sitaramam.mp4",
      newreleased: false,
      agerating: "R",
      duration: "2h 25m",
      cast: [
        "Chris Hemsworth",
        "Rudhraksh Jaiswal",
        "Golshifteh Farahani",
        "Adam Bessa",
      ],
      director: "Sam Hargrave",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/english/f1.jpeg",
      titl: "F1: The Movie",
      description:
          "Behind the scenes of Formula 1 racing, capturing passion and risks.",
      istop10: true,
      releaseYear: "2025",
      video: "assets/video/movies_video/malayalam/premalu.mp4",
      newreleased: true,
      agerating: "PG-13",
      duration: "2h 10m",
      cast: [
        "Lewis Hamilton",
        "Max Verstappen",
        "Sebastian Vettel",
        "Fernando Alonso",
      ],
      director: "Molly Moss",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/english/FightClub.jpeg",
      titl: "Fight Club",
      description:
          "An insomniac office worker forms an underground fight club.",
      istop10: false,
      releaseYear: "1999",
      video: "assets/video/movies_video/malayalam/lucifer.mp4",
      newreleased: false,
      agerating: "R",
      duration: "2h 19m",
      cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf"],
      director: "David Fincher",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/english/godfather.jpeg",
      titl: "The Godfather",
      description:
          "The aging patriarch of an organized crime dynasty transfers control to his son.",
      istop10: false,
      releaseYear: "1972",
      video: "assets/video/movies_video/malayalam/lokaj.mp4",
      newreleased: false,
      agerating: "R",
      duration: "2h 55m",
      cast: ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton"],
      director: "Francis Ford Coppola",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/Inception.jpeg",
      titl: "Inception",
      description:
          "A thief enters people’s dreams to steal secrets but faces personal demons.",
      istop10: false,
      releaseYear: "2010",
      video: "assets/video/movies_video/malayalam/koode.mp4",
      newreleased: false,
      agerating: "PG-13",
      duration: "2h 28m",
      cast: [
        "Leonardo DiCaprio",
        "Joseph Gordon-Levitt",
        "Elliot Page",
        "Tom Hardy",
      ],
      director: "Christopher Nolan",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/Interstellar(2014).jpeg",
      titl: "Interstellar",
      description:
          "A team of explorers travel through a wormhole to save humanity.",
      istop10: true,
      releaseYear: "2014",
      video: "assets/video/movies_video/malayalam/lucifer.mp4",
      newreleased: false,
      agerating: "PG-13",
      duration: "2h 49m",
      cast: [
        "Matthew McConaughey",
        "Anne Hathaway",
        "Jessica Chastain",
        "Michael Caine",
      ],
      director: "Christopher Nolan",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/Jumanji.jpeg",
      titl: "Jumanji",
      description:
          "When a mysterious board game sucks players into a wild jungle adventure, they must finish it to survive.",
      istop10: false,
      releaseYear: "2019",
      video: "assets/video/movies_video/english/jumanji2019.mp4",
      newreleased: false,
      agerating: "PG-13",
      duration: "1h 59m",
      cast: ["Dwayne Johnson", "Jack Black", "Kevin Hart", "Karen Gillan"],
      director: "Jake Kasdan",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/english/marcian.jpeg",
      titl: "The Martian",
      description:
          "An astronaut left behind on Mars uses his wit and science to survive and signal Earth for rescue.",
      istop10: false,
      releaseYear: "2014",
      video: "assets/video/movies_video/english/themartian.mp4",
      newreleased: false,
      agerating: "PG-13",
      duration: "2h 24m",
      cast: ["Matt Damon", "Jessica Chastain", "Kristen Wiig", "Jeff Daniels"],
      director: "Ridley Scott",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/missionimpossible.jpeg",
      titl: "Mission: Impossible",
      description:
          "An elite agent must rally his team for another high-stakes global mission filled with espionage and danger.",
      istop10: true,
      releaseYear: "2025",
      video: "assets/video/movies_video/english/missionimpossible2025.mp4",
      newreleased: true,
      agerating: "PG-13",
      duration: "2h 49m",
      cast: ["Tom Cruise", "Hayley Atwell", "Simon Pegg", "Ving Rhames"],
      director: "Christopher McQuarrie",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/english/SavingPrivateRyan.jpeg",
      titl: "Saving Private Ryan",
      description:
          "In WWII, a small squad goes behind enemy lines to save one man — the mission challenges their courage and faith.",
      istop10: false,
      releaseYear: "2004",
      video: "assets/video/movies_video/english/savingprivateryan.mp4",
      newreleased: false,
      agerating: "R",
      duration: "2h 49m",
      cast: ["Tom Hanks", "Matt Damon", "Tom Sizemore", "Edward Burns"],
      director: "Steven Spielberg",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/english/ShawshankRedemption.jpeg",
      titl: "The Shawshank Redemption",
      description:
          "Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.",
      istop10: false,
      releaseYear: "1994",
      video: "assets/video/movies_video/english/shawshankredemption.mp4",
      newreleased: false,
      agerating: "R",
      duration: "2h 22m",
      cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
      director: "Frank Darabont",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/english/The Prestige (2006).jpeg",
      titl: "The Prestige",
      description:
          "Two rival magicians engage in a bitter competition to create the ultimate illusion, with dangerous consequences.",
      istop10: false,
      releaseYear: "2006",
      video: "assets/video/movies_video/english/theprestige.mp4",
      newreleased: false,
      agerating: "PG-13",
      duration: "2h 10m",
      cast: [
        "Christian Bale",
        "Hugh Jackman",
        "Michael Caine",
        "Scarlett Johansson",
      ],
      director: "Christopher Nolan",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/TheDarkKnight.jpeg",
      titl: "The Dark Knight Rises",
      description:
          "Batman returns to face a rising threat in Gotham while confronting his own legacy and morality.",
      istop10: false,
      releaseYear: "2012",
      video: "assets/video/movies_video/english/thedarkknightrises.mp4",
      newreleased: false,
      agerating: "PG-13",
      duration: "2h 44m",
      cast: [
        "Christian Bale",
        "Tom Hardy",
        "Anne Hathaway",
        "Joseph Gordon-Levitt",
      ],
      director: "Christopher Nolan",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/english/titanic.jpeg",
      titl: "Titanic",
      description:
          "A romance aboard the doomed RMS Titanic becomes a fight for survival when the ship sinks.",
      istop10: true,
      releaseYear: "1997",
      video: "assets/video/movies_video/english/titanic1997.mp4",
      newreleased: false,
      agerating: "PG-13",
      duration: "3h 14m",
      cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates"],
      director: "James Cameron",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/TopGunMaverick.jpeg",
      titl: "Top Gun: Maverick",
      description:
          "A veteran pilot returns to train a new generation of Top Gun flyers while confronting his past and new threats.",
      istop10: false,
      releaseYear: "2022",
      video: "assets/video/movies_video/english/topgunmaverick.mp4",
      newreleased: false,
      agerating: "PG-13",
      duration: "2h 11m",
      cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly", "Jon Hamm"],
      director: "Joseph Kosinski",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/english/wolfof.jpeg",
      titl: "The Wolf of Wall Street",
      description:
          "Based on a true story, a stockbroker’s rise and fall is marked by greed, sex, and corruption on Wall Street.",
      istop10: false,
      releaseYear: "2013",
      video: "assets/video/movies_video/english/thewolfofwallstreet.mp4",
      newreleased: false,
      agerating: "R",
      duration: "3h 0m",
      cast: [
        "Leonardo DiCaprio",
        "Jonah Hill",
        "Margot Robbie",
        "Matthew McConaughey",
      ],
      director: "Martin Scorsese",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/worlswar2.jpeg",
      titl: "World War Z",
      description:
          "A former UN investigator traverses the world to stop a global zombie pandemic and save humanity.",
      istop10: true,
      releaseYear: "2013",
      video: "assets/video/movies_video/english/worldwarz.mp4",
      newreleased: true,
      agerating: "PG-13",
      duration: "1h 56m",
      cast: ["Brad Pitt", "Mireille Enos", "Elyes Gabel", "James Badge Dale"],
      director: "Marc Forster",
    ),
  ],
  'Tamil': [
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/Dragon.jpeg",
      titl: "Dragon",
      description:
          "A college dropout cons his way into a high-paying job but must confront the lies he built.",
      istop10: true,
      releaseYear: "2025",
      video: "assets/video/movies_video/hindi/TigerZindaHai.mp4",
      newreleased: true,
      agerating: "U/A 13+",
      duration: "2h 37m",
      cast: [
        "Pradeep Ranganathan",
        "Anupama Parameswaran",
        "Kayadu Lohar",
        "Mysskin",
      ],
      director: "Ashwath Marimuthu",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/tamil/vikram.jpeg",
      titl: "Vikram",
      description:
          "A masked black-ops agent takes on a drug syndicate in a high stakes action thriller.",
      istop10: false,
      releaseYear: "2022",
      video: "assets/video/movies_video/malayalam/premam.mp4",
      newreleased: false,
      agerating: "U/A 16+",
      duration: "2h 54m",
      cast: ["Kamal Haasan", "Vijay Sethupathi", "Fahadh Faasil", "Narain"],
      director: "Lokesh Kanagaraj",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/viduthalai.jpeg",
      titl: "Viduthalai 2",
      description:
          "The sequel to a tense rural justice saga where one man fights against powerful forces.",
      istop10: false,
      releaseYear: "2024",
      video: "assets/video/movies_video/hindi/laalsingh.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 28m",
      cast: ["Soori", "R. Parthiban", "Gowri Munjal", "Vela Ramamoorthy"],
      director: "Vetri Maaran",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/tamil/bison.jpeg",
      titl: "Bison: Kaalamaadan",
      description:
          "A rising Kabaddi star takes on his destiny in this gritty sports drama.",
      istop10: false,
      releaseYear: "2025",
      video: "assets/video/movies_video/malayalam/lucifer.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 24m",
      cast: ["Dhruv Vikram", "Anupama Parameswaran", "Lal", "Pasupathi"],
      director: "Mari Selvaraj",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/coolie.jpeg",
      titl: "Coolie",
      description:
          "An ordinary man takes an extraordinary stand in the face of injustice.",
      istop10: false,
      releaseYear: "2025",
      video: "assets/video/movies_video/hindi/msdhoni.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 20m",
      cast: [
        "Dulquer Salmaan",
        "Meenakshi Chaudhary",
        "Prasanna",
        "R. Sarathkumar",
      ],
      director: "Venky Atluri",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/tamil/vettyan.jpeg",
      titl: "Vettaiyan",
      description:
          "A vigilante rises in the under-belly of the city, seeking redemption.",
      istop10: false,
      releaseYear: "2024",
      video: "assets/video/movies_video/malayalam/sitaramam.mp4",
      newreleased: false,
      agerating: "U/A 16+",
      duration: "2h 10m",
      cast: [
        "Silambarasan",
        "Gautham Vasudev Menon",
        "Pooja Hegde",
        "Yogi Babu",
      ],
      director: "Siva",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/tamil/petta.jpeg",
      titl: "Petta",
      description:
          "A hostel warden with a mysterious past returns to settle old scores.",
      istop10: false,
      releaseYear: "2019",
      video: "assets/video/movies_video/hindi/hamari.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 39m",
      cast: ["Rajinikanth", "Karisma Kapoor", "Vijay Sethupathi", "Simran"],
      director: "Karthik Subbaraj",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/Meiyazhagan.jpeg",
      titl: "Meiyazhagan",
      description:
          "A young man learns life lessons through unexpected friendships and love.",
      istop10: false,
      releaseYear: "2024",
      video: "assets/video/movies_video/malayalam/premalu.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 05m",
      cast: ["Nani", "Lloyd Vijay", "Priyanka Arul Mohan", "Anagha"],
      director: "Vignesh Shivn",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/maveeran.jpeg",
      titl: "Maaveeran",
      description: "An unlikely hero stands up when his city needs him most.",
      istop10: false,
      releaseYear: "2023",
      video: "assets/video/movies_video/hindi/laalata.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 25m",
      cast: ["Sivakarthikeyan", "Aditi Shankar", "Karunakaran", "Skr"],
      director: "M. Natesan",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/markantony.jpeg",
      titl: "Mark Antony",
      description:
          "A fun-filled action entertainer about a bus driver with hidden skills.",
      istop10: true,
      releaseYear: "2023",
      video: "assets/video/movies_video/malayalam/joji.mp4",
      newreleased: true,
      agerating: "U/A 13+",
      duration: "2h 30m",
      cast: ["Vijay Antony", "Madhurima", "Anandaraj", "Daniel Balaji"],
      director: "Adhik Vijay",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/tamil/mangatha.jpeg",
      titl: "Mangatha",
      description:
          "An undercover cop goes rogue to bring down the crime ring he once worked for.",
      istop10: false,
      releaseYear: "2024",
      video: "assets/video/movies_video/hindi/dilwale.mp4",
      newreleased: false,
      agerating: "U/A 16+",
      duration: "2h 22m",
      cast: ["Vijay Antony", "Ayshika R Parikh", "KR Gokul", "Sunil Ravi"],
      director: "Bobby Panda",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/Maharaja.jpeg",
      titl: "Maharaja",
      description:
          "A rich heir finds purpose when he defends the common people.",
      istop10: false,
      releaseYear: "2024",
      video: "assets/video/movies_video/malayalam/thudarum.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 15m",
      cast: [
        "Vijay Antony",
        "Meenakshi Chaudhary",
        "H-A Priyadarshan",
        "Yogi Babu",
      ],
      director: "Sethu Madhan",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/tamil/mahaan.jpeg",
      titl: "Mahaan",
      description:
          "A vigilante returns to heroism when his family is threatened.",
      istop10: false,
      releaseYear: "2022",
      video: "assets/video/movies_video/hindi/aedilhai.mp4",
      newreleased: false,
      agerating: "U/A 16+",
      duration: "2h 32m",
      cast: ["Vikram", "Vani Kashyap", "Isha Talwar", "Santhosh Prathap"],
      director: "Karthik Subbaraj",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/love2day.jpeg",
      titl: "Love Today",
      description:
          "Two strangers swap phones for a day and realise life’s unexpected surprises.",
      istop10: false,
      releaseYear: "2022",
      video: "assets/video/movies_video/hindi/laapataladies.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 14m",
      cast: [
        "Sivakarthikeyan",
        "Sanya Malhotra",
        "Arun Alexander",
        "Soham Panda",
      ],
      director: "Pradeep Ranganathan",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/tamil/leo.jpeg",
      titl: "Leo",
      description:
          "An undercover cop hunts a serial killer while battling his past.",
      istop10: false,
      releaseYear: "2023",
      video: "assets/video/movies_video/malayalam/sitaramam.mp4",
      newreleased: false,
      agerating: "U/A 16+",
      duration: "2h 33m",
      cast: ["Vijay", "Trisha Krishnan", "Arjun Das", "Mysskin"],
      director: "Lokesh Kanagaraj",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/tamil/kaithi.jpeg",
      titl: "Kaithi",
      description:
          "A released prisoner spends one night helping police during a drug bust to see his daughter again.",
      istop10: false,
      releaseYear: "2019",
      video: "assets/video/movies_video/hindi/dilbechara.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "1h 57m",
      cast: ["Karthi", "Narain", "Arun Pandian", "Sujatha"],
      director: "Lokesh Kanagaraj",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/Jailer.jpeg",
      titl: "Jailer",
      description:
          "A retired prison warden returns to uncover a dangerous conspiracy.",
      istop10: true,
      releaseYear: "2023",
      video: "assets/video/movies_video/hindi/aedilhai.mp4",
      newreleased: true,
      agerating: "U/A 13+",
      duration: "2h 45m",
      cast: [
        "Rajinikanth",
        "Vijay Sethupathi",
        "Ramya Krishnan",
        "Sunil S Réddy",
      ],
      director: "Nelson",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/jaibheem.jpeg",
      titl: "Jai Bhim",
      description:
          "A lawyer fights for the rights of marginalized people in this legal drama.",
      istop10: false,
      releaseYear: "2021",
      video: "assets/video/movies_video/malayalam/varathan.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 37m",
      cast: ["Suriya", "Lijomol Jose", "Manikandan", "Prakash Raj"],
      director: "T J Gnanavel",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/hit.jpeg",
      titl: "HIT: The 3rd Case",
      description:
          "A cold case investigator confronts his toughest challenge yet.",
      istop10: true,
      releaseYear: "2025",
      video: "assets/video/movies_video/hindi/laalata.mp4",
      newreleased: true,
      agerating: "U/A 16+",
      duration: "2h 20m",
      cast: ["Vishal", "Rakul Preet Singh", "Arun Vijay", "Bhumika Chawla"],
      director: "Soori",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/heysinamika.jpeg",
      titl: "Hey Sinamika",
      description:
          "An actress meets an obsessed admirer, sparking unexpected change.",
      istop10: true,
      releaseYear: "2022",
      video: "assets/video/movies_video/hindi/laalsingh.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 26m",
      cast: [
        "Hannah Kalyani",
        "Preethi Shivram",
        "Sanam Puri",
        "Vijay Sethupathi",
      ],
      director: "Brinda",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/96.jpeg",
      titl: "96",
      description:
          "Two high school sweethearts reconnect years later, reliving memories.",
      istop10: false,
      releaseYear: "2018",
      video: "assets/video/movies_video/malayalam/koode.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 12m",
      cast: [
        "Vijay Sethupathi",
        "Trisha Krishnan",
        "Sam Glen",
        "Mahanadhi Shankar",
      ],
      director: "C Prem Kumar",
    ),
  ],
  'Top 10': [
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/Dragon.jpeg",
      titl: "Dragon",
      description:
          "A college dropout cons his way into a high-paying job but must confront the lies he built.",
      istop10: true,
      releaseYear: "2025",
      video: "assets/video/movies_video/hindi/TigerZindaHai.mp4",
      newreleased: true,
      agerating: "U/A 13+",
      duration: "2h 37m",
      cast: [
        "Pradeep Ranganathan",
        "Anupama Parameswaran",
        "Kayadu Lohar",
        "Mysskin",
      ],
      director: "Ashwath Marimuthu",
    ),
    MoviesModel(
      false,
      thumbail: "assets/images/movies/english/f1.jpeg",
      titl: "F1: The Movie",
      description:
          "Behind the scenes of Formula 1 racing, capturing passion and risks.",
      istop10: true,
      releaseYear: "2025",
      video: "assets/video/movies_video/malayalam/premalu.mp4",
      newreleased: true,
      agerating: "PG-13",
      duration: "2h 10m",
      cast: [
        "Lewis Hamilton",
        "Max Verstappen",
        "Sebastian Vettel",
        "Fernando Alonso",
      ],
      director: "Molly Moss",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/Extraction2.jpeg",
      titl: "Extraction II",
      description:
          "Tyler Rake returns for a mission that tests his limits and resolve.",
      istop10: true,
      releaseYear: "2023",
      video: "assets/video/movies_video/malayalam/sitaramam.mp4",
      newreleased: false,
      agerating: "R",
      duration: "2h 25m",
      cast: [
        "Chris Hemsworth",
        "Rudhraksh Jaiswal",
        "Golshifteh Farahani",
        "Adam Bessa",
      ],
      director: "Sam Hargrave",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/markantony.jpeg",
      titl: "Mark Antony",
      description:
          "A fun-filled action entertainer about a bus driver with hidden skills.",
      istop10: true,
      releaseYear: "2023",
      video: "assets/video/movies_video/malayalam/joji.mp4",
      newreleased: true,
      agerating: "U/A 13+",
      duration: "2h 30m",
      cast: ["Vijay Antony", "Madhurima", "Anandaraj", "Daniel Balaji"],
      director: "Adhik Vijay",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/arrival.jpeg",
      titl: "Arrival",
      description:
          "A linguist works to communicate with aliens who have landed on Earth.",
      istop10: true,
      releaseYear: "2016",
      video: "assets/video/movies_video/malayalam/virus.mp4",
      newreleased: true,
      agerating: "PG-13",
      duration: "1h 56m",
      cast: [
        "Amy Adams",
        "Jeremy Renner",
        "Forest Whitaker",
        "Michael Stuhlbarg",
      ],
      director: "Denis Villeneuve",
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/thudarum.jpg',
      titl: 'Thudarum',
      description:
          "Thudarum is an upcoming crime drama directed by Tharun Moorthy that delves into mystery and moral conflict in a small Kerala town.",
      istop10: true,
      releaseYear: '2025',
      video: 'assets/video/movies_video/malayalam/thudarum.mp4',
      newreleased: true,
      agerating: 'U/A 13+',
      duration: '2h 30m',
      cast: ['Mohanlal', 'Shobhana', 'Bharathiraja', 'Thomas Mathew'],
      director: 'Tharun Moorthy',
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/heysinamika.jpeg",
      titl: "Hey Sinamika",
      description:
          "An actress meets an obsessed admirer, sparking unexpected change.",
      istop10: true,
      releaseYear: "2022",
      video: "assets/video/movies_video/hindi/laalsingh.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 26m",
      cast: [
        "Hannah Kalyani",
        "Preethi Shivram",
        "Sanam Puri",
        "Vijay Sethupathi",
      ],
      director: "Brinda",
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/hindi/october.jpg',
      titl: 'October',
      description:
          'A subtle love story about care, loss, and emotional growth.',
      istop10: true,
      releaseYear: '2018',
      video: 'assets/video/movies_video/hindi/october.mp4',
      newreleased: false,
      agerating: 'U',
      duration: '1h 55m',
      cast: ['Varun Dhawan', 'Banita Sandhu'],
      director: 'Shoojit Sircar',
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/hindi/saiyyara.jpg',
      titl: 'Saiyaara',
      description: 'A romantic drama inspired by timeless love and separation.',
      istop10: true,
      releaseYear: '2024',
      video: 'assets/video/movies_video/hindi/Saiyaara.mp4',
      newreleased: true,
      agerating: 'U/A',
      duration: '2h 18m',
      cast: [],
      director: 'Unknown',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/hindi/dilbechara.jpg',
      titl: 'Dil Bechara',
      description:
          'An emotional journey of love and life between two young cancer patients.',
      istop10: true,
      releaseYear: '2020',
      video: 'assets/video/movies_video/hindi/dilbechara.mp4',
      newreleased: false,
      agerating: 'U/A',
      duration: '1h 41m',
      cast: ['Sushant Singh Rajput', 'Sanjana Sanghi'],
      director: 'Mukesh Chhabra',
    ),
    MoviesModel(
      false,
      thumbail: 'assets/images/movies/malayalam/Premalu.jpg',
      titl: 'Premalu',
      description:
          "A fun-filled romantic comedy set in Hyderabad, following Sachin’s misadventures in love and friendship.",
      istop10: true,
      releaseYear: '2024',
      video: 'assets/video/movies_video/malayalam/premalu.mp4',
      newreleased: true,
      agerating: 'U/A 13+',
      duration: '2h 26m',
      cast: ['Naslen', 'Mamitha Baiju', 'Shyam Mohan', 'Akhila Bhargavan'],
      director: 'Girish A D',
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/hindi/lalsingh.jpg',
      titl: 'Laal Singh Chaddha',
      description:
          'A retelling of Forrest Gump in an Indian context, following a kind-hearted man’s journey.',
      istop10: true,
      releaseYear: '2022',
      video: 'assets/video/movies_video/hindi/laalsingh.mp4',
      newreleased: false,
      agerating: 'U/A',
      duration: '2h 39m',
      cast: ['Aamir Khan', 'Kareena Kapoor', 'Mona Singh'],
      director: 'Advait Chandan',
    ),
  ],
  'Netflix': [
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/96.jpeg",
      titl: "96",
      description:
          "Two high school sweethearts reconnect years later, reliving memories.",
      istop10: false,
      releaseYear: "2018",
      video: "assets/video/movies_video/malayalam/koode.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 12m",
      cast: [
        "Vijay Sethupathi",
        "Trisha Krishnan",
        "Sam Glen",
        "Mahanadhi Shankar",
      ],
      director: "C Prem Kumar",
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/malayalam/Romancham.jpg',
      titl: 'Romancham',
      description:
          "A group of friends experiment with a Ouija board, leading to hilarious and spooky consequences.",
      istop10: true,
      releaseYear: '2023',
      video: 'assets/video/movies_video/malayalam/Romancham.mp4',
      newreleased: true,
      agerating: 'U/A 13+',
      duration: '2h 10m',
      cast: ['Soubin Shahir', 'Arjun Ashokan', 'Sajin Gopu', 'Abin Bino'],
      director: 'Jithu Madhavan',
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/deappool.jpeg",
      titl: "Deadpool & Wolverine",
      description:
          "Deadpool and Wolverine team up for chaotic, action-packed adventures.",
      istop10: false,
      releaseYear: "2024",
      video: "assets/video/movies_video/malayalam/premam.mp4",
      newreleased: false,
      agerating: "R",
      duration: "2h 10m",
      cast: ["Ryan Reynolds", "Hugh Jackman", "Morena Baccarin", "Josh Brolin"],
      director: "David Leitch",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/Jailer.jpeg",
      titl: "Jailer",
      description:
          "A retired prison warden returns to uncover a dangerous conspiracy.",
      istop10: true,
      releaseYear: "2023",
      video: "assets/video/movies_video/hindi/aedilhai.mp4",
      newreleased: true,
      agerating: "U/A 13+",
      duration: "2h 45m",
      cast: [
        "Rajinikanth",
        "Vijay Sethupathi",
        "Ramya Krishnan",
        "Sunil S Réddy",
      ],
      director: "Nelson",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/dontbreath.jpeg",
      titl: "Don't Breathe 2",
      description:
          "The blind man faces new threats while trying to protect a young girl.",
      istop10: false,
      releaseYear: "2021",
      video: "assets/video/movies_video/malayalam/joji.mp4",
      newreleased: false,
      agerating: "R",
      duration: "1h 38m",
      cast: ["Stephen Lang", "Bridger Zadina", "Madelyn Grace", "Jane Levy"],
      director: "Rodo Sayagues",
    ),

    MoviesModel(
      true,
      thumbail: 'assets/images/movies/malayalam/Padakkalam.jpeg',
      titl: 'Padakkalam',
      description:
          "Four students face a supernatural adventure when their new professor turns their world upside down.",
      istop10: false,
      releaseYear: '2025',
      video: 'assets/video/movies_video/malayalam/premalu.mp4',
      newreleased: true,
      agerating: 'U',
      duration: '123 minutes',
      cast: [
        'Suraj Venjaramoodu as Professor Shaji K K',
        'Sharaf U Dheen as Professor Renjith',
        'Sandeep Pradeep as Jithin',
        'Saaf as Kannan',
      ],
      director: 'Manu Swaraj',
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/Extraction2.jpeg",
      titl: "Extraction II",
      description:
          "Tyler Rake returns for a mission that tests his limits and resolve.",
      istop10: true,
      releaseYear: "2023",
      video: "assets/video/movies_video/malayalam/sitaramam.mp4",
      newreleased: false,
      agerating: "R",
      duration: "2h 25m",
      cast: [
        "Chris Hemsworth",
        "Rudhraksh Jaiswal",
        "Golshifteh Farahani",
        "Adam Bessa",
      ],
      director: "Sam Hargrave",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/coolie.jpeg",
      titl: "Coolie",
      description:
          "An ordinary man takes an extraordinary stand in the face of injustice.",
      istop10: false,
      releaseYear: "2025",
      video: "assets/video/movies_video/hindi/msdhoni.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 20m",
      cast: [
        "Dulquer Salmaan",
        "Meenakshi Chaudhary",
        "Prasanna",
        "R. Sarathkumar",
      ],
      director: "Venky Atluri",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/love2day.jpeg",
      titl: "Love Today",
      description:
          "Two strangers swap phones for a day and realise life’s unexpected surprises.",
      istop10: false,
      releaseYear: "2022",
      video: "assets/video/movies_video/hindi/laapataladies.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 14m",
      cast: [
        "Sivakarthikeyan",
        "Sanya Malhotra",
        "Arun Alexander",
        "Soham Panda",
      ],
      director: "Pradeep Ranganathan",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/missionimpossible.jpeg",
      titl: "Mission: Impossible",
      description:
          "An elite agent must rally his team for another high-stakes global mission filled with espionage and danger.",
      istop10: true,
      releaseYear: "2025",
      video: "assets/video/movies_video/english/missionimpossible2025.mp4",
      newreleased: true,
      agerating: "PG-13",
      duration: "2h 49m",
      cast: ["Tom Cruise", "Hayley Atwell", "Simon Pegg", "Ving Rhames"],
      director: "Christopher McQuarrie",
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/malayalam/2018.jpg',
      titl: '2018',
      description:
          "Based on the real-life 2018 Kerala floods, the film tells inspiring stories of human courage and unity.",
      istop10: true,
      releaseYear: '2023',
      video: 'assets/video/movies_video/malayalam/joji.mp4',
      newreleased: false,
      agerating: 'U/A 13+',
      duration: '2h 38m',
      cast: [
        'Tovino Thomas',
        'Kunchacko Boban',
        'Aparna Balamurali',
        'Asif Ali',
      ],
      director: 'Jude Anthany Joseph',
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/hindi/crew.jpg',
      titl: 'Crew',
      description:
          'Three air hostesses get caught in a web of deceit, money, and mayhem.',
      istop10: true,
      releaseYear: '2024',
      video: 'assets/video/movies_video/hindi/crew.mp4',
      newreleased: true,
      agerating: 'U/A',
      duration: '2h 15m',
      cast: ['Tabu', 'Kareena Kapoor Khan', 'Kriti Sanon'],
      director: 'Rajesh Krishnan',
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/viduthalai.jpeg",
      titl: "Viduthalai 2",
      description:
          "The sequel to a tense rural justice saga where one man fights against powerful forces.",
      istop10: false,
      releaseYear: "2024",
      video: "assets/video/movies_video/hindi/laalsingh.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 28m",
      cast: ["Soori", "R. Parthiban", "Gowri Munjal", "Vela Ramamoorthy"],
      director: "Vetri Maaran",
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/hindi/thamasha.jpg',
      titl: 'Tamasha',
      description:
          'A man struggles to find his true self beyond societal expectations.',
      istop10: false,
      releaseYear: '2015',
      video: 'assets/video/movies_video/hindi/tamasha.mp4',
      newreleased: false,
      agerating: 'U/A',
      duration: '2h 19m',
      cast: ['Ranbir Kapoor', 'Deepika Padukone'],
      director: 'Imtiaz Ali',
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/maveeran.jpeg",
      titl: "Maaveeran",
      description: "An unlikely hero stands up when his city needs him most.",
      istop10: false,
      releaseYear: "2023",
      video: "assets/video/movies_video/hindi/laalata.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 25m",
      cast: ["Sivakarthikeyan", "Aditi Shankar", "Karunakaran", "Skr"],
      director: "M. Natesan",
    ),
    MoviesModel(
      true,
      thumbail: 'assets/images/movies/malayalam/luckybaskhar.jpg',
      titl: 'Lucky Baskhar',
      description:
          "A middle-class man discovers a mysterious opportunity that changes his financial destiny.",
      istop10: true,
      releaseYear: '2024',
      video: 'assets/video/movies_video/malayalam/lucifer.mp4',
      newreleased: true,
      agerating: 'U/A 13+',
      duration: '2h 30m',
      cast: [
        'Dulquer Salmaan',
        'Meenakshi Chaudhary',
        'R. Sarathkumar',
        'Prasanna',
      ],
      director: 'Venky Atluri',
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/Jumanji.jpeg",
      titl: "Jumanji",
      description:
          "When a mysterious board game sucks players into a wild jungle adventure, they must finish it to survive.",
      istop10: false,
      releaseYear: "2019",
      video: "assets/video/movies_video/english/jumanji2019.mp4",
      newreleased: false,
      agerating: "PG-13",
      duration: "1h 59m",
      cast: ["Dwayne Johnson", "Jack Black", "Kevin Hart", "Karen Gillan"],
      director: "Jake Kasdan",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/english/Inception.jpeg",
      titl: "Inception",
      description:
          "A thief enters people’s dreams to steal secrets but faces personal demons.",
      istop10: false,
      releaseYear: "2010",
      video: "assets/video/movies_video/malayalam/koode.mp4",
      newreleased: false,
      agerating: "PG-13",
      duration: "2h 28m",
      cast: [
        "Leonardo DiCaprio",
        "Joseph Gordon-Levitt",
        "Elliot Page",
        "Tom Hardy",
      ],
      director: "Christopher Nolan",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/jaibheem.jpeg",
      titl: "Jai Bhim",
      description:
          "A lawyer fights for the rights of marginalized people in this legal drama.",
      istop10: false,
      releaseYear: "2021",
      video: "assets/video/movies_video/malayalam/varathan.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 37m",
      cast: ["Suriya", "Lijomol Jose", "Manikandan", "Prakash Raj"],
      director: "T J Gnanavel",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/Maharaja.jpeg",
      titl: "Maharaja",
      description:
          "A rich heir finds purpose when he defends the common people.",
      istop10: false,
      releaseYear: "2024",
      video: "assets/video/movies_video/malayalam/thudarum.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 15m",
      cast: [
        "Vijay Antony",
        "Meenakshi Chaudhary",
        "H-A Priyadarshan",
        "Yogi Babu",
      ],
      director: "Sethu Madhan",
    ),
    MoviesModel(
      true,
      thumbail: "assets/images/movies/tamil/Meiyazhagan.jpeg",
      titl: "Meiyazhagan",
      description:
          "A young man learns life lessons through unexpected friendships and love.",
      istop10: false,
      releaseYear: "2024",
      video: "assets/video/movies_video/malayalam/premalu.mp4",
      newreleased: false,
      agerating: "U/A 13+",
      duration: "2h 05m",
      cast: ["Nani", "Lloyd Vijay", "Priyanka Arul Mohan", "Anagha"],
      director: "Vignesh Shivn",
    ),
  ],
};
